### ISSUE TITLE
Update the UI to support switching to French

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notifier-api#22]
**What?**
- Put in toggle to switch the UI to French that sets a session variable. 
- Detects browser language

**Why?**
- Official Language support
- Usability testing
- I imagine we will have French users

**Comment by timarney** [comment]
This commit https://github.com/cds-snc/notifier-admin/commit/89f06d8c9d0200d186bb326ae2643aba247ec37e adds the language toggle.

Notes: 

- Currently only the /documentation link will show translations as none of the other templates are setup yet.

- If the language isn't set it will default to the users lang via the browser request.
