### ISSUE TITLE
Update Favicon From Crown to Mapleleaf favicon

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notifier-api#41]
**What?**
- Crown favicon should be canada.ca maple leaf fav icon
- Can we change the Page Meta Title too so it doesn't say Gov.uk Notify?

**Why?**
- We don't want people to think we are monarchists

**Comment by willeybryan** [comment]
Did we rip out the Meta info on this ticket too?

Because we shoud change the meta title to Notification and meta description to "Notificaiton lets you send emails and text messages to your users." so when we post it in Slack and stuff it doesn't look like we are directing people to Gov.uk notify.

**Comment by timarney** [comment]
Just pushed up a change for that - seems to pull from the signed-out template (which makes sense).  We'll see if that does the trick.
